const ERRORS = {
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL: 'INTERNAL',
  BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
  USER_NOT_AUTHORIZED: 'USER_NOT_AUTHORIZED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  NO_AVAILABLE_BOOKS: 'NO_AVAILABLE_BOOKS',
};

module.exports = {
  ERRORS,
};
